---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-virtual-env-clody-io-v1-virtualenvinfra
  failurePolicy: Fail
  name: mvirtualenvinfra.kb.io
  rules:
  - apiGroups:
    - virtual-env.clody.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualenvinfras
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-virtual-env-clody-io-v1-virtualenvinfra
  failurePolicy: Fail
  name: vvirtualenvinfra.kb.io
  rules:
  - apiGroups:
    - virtual-env.clody.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualenvinfras
  sideEffects: None
