---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - virual-env.clody.io
  resources:
  - virualenvs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - virual-env.clody.io
  resources:
  - virualenvs/finalizers
  verbs:
  - update
- apiGroups:
  - virual-env.clody.io
  resources:
  - virualenvs/status
  verbs:
  - get
  - patch
  - update
