---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - virtual-env.clody.io
  resources:
  - virtualenvs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - virtual-env.clody.io
  resources:
  - virtualenvs/finalizers
  verbs:
  - update
- apiGroups:
  - virtual-env.clody.io
  resources:
  - virtualenvs/status
  verbs:
  - get
  - patch
  - update
