apiVersion: virtual-env.clody.io/v1
kind: LocalRoom
metadata:
  labels:
    app.kubernetes.io/name: localroom
    app.kubernetes.io/instance: localroom-sample
    app.kubernetes.io/part-of: nebula
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: nebula
  name: localroom-sample
spec:
  # TODO(user): Add fields here
